import { Playlist } from './types';
import { beforeAll, describe, expect, it } from 'vitest';
import { hasToken, makeMock } from '../../../testingTools';
import { getPlaylistItems } from './getPlaylistItems';

describe('getPlaylistItems', () => {
  beforeAll(() => {
    makeMock('v1/playlists/37i9dQZF1DX5g856aiKiDS/tracks', {
      handler: (req) => {
        if (!hasToken(req.headers as any))
          return {
            statusCode: 401,
          };
        return {
          statusCode: 200,
          data: mockedPlaylistItems,
        };
      },
    });
    makeMock(
      '/v1/playlists/37i9dQZF1DX5g856aiKiDS/tracks?limit=10&market=KR&offset=5',
      {
        handler: (req) => {
          if (!hasToken(req.headers as any))
            return {
              statusCode: 401,
            };
          const params = new URLSearchParams(req.path.split('?')[1]);
          const [limit, offset, market] = ['limit', 'offset', 'market'].map(
            (param) => params.get(param)
          );
          return {
            statusCode: 200,
            data: {
              limit,
              offset,
              market,
            },
          };
        },
      }
    );
  });
  it('should return a function', () => {
    expect(typeof getPlaylistItems('37i9dQZF1DX5g856aiKiDS')).toBe('function');
  });
  it('should fetch playlist items', async () => {
    const playlist = await getPlaylistItems('37i9dQZF1DX5g856aiKiDS')({
      token: 'token',
    } as any);
    expect(playlist).toEqual(mockedPlaylistItems);
  });
  it('should pass through params', async () => {
    const { offset, limit, market } = (await getPlaylistItems(
      '37i9dQZF1DX5g856aiKiDS',
      {
        offset: 5,
        limit: 10,
        market: 'KR',
      }
    )({
      token: 'token',
    } as any)) as any;
    expect(offset).toEqual('5');
    expect(limit).toEqual('10');
    expect(market).toEqual('KR');
  });
});

const mockedPlaylistItems: Playlist['tracks'] = {
  href: 'https://api.spotify.com/v1/playlists/37i9dQZF1DXdVyc8LtLi96/tracks?offset=0&limit=1&locale=en-US,en;q=0.9,ko-KR;q=0.8,ko;q=0.7',
  items: [
    {
      added_at: '2022-09-22T07:55:11Z',
      added_by: {
        external_urls: {
          spotify: 'https://open.spotify.com/user/',
        },
        href: 'https://api.spotify.com/v1/users/',
        id: '',
        type: 'user',
        uri: 'spotify:user:',
      },
      is_local: false,
      primary_color: null,
      track: {
        album: {
          album_type: 'single',
          artists: [
            {
              external_urls: {
                spotify:
                  'https://open.spotify.com/artist/2HwBdENnqvDpXaeLBMBtqF',
              },
              href: 'https://api.spotify.com/v1/artists/2HwBdENnqvDpXaeLBMBtqF',
              id: '2HwBdENnqvDpXaeLBMBtqF',
              name: 'Sezja',
              type: 'artist',
              uri: 'spotify:artist:2HwBdENnqvDpXaeLBMBtqF',
            },
          ],
          available_markets: [
            'AD',
            'AE',
            'AG',
            'AL',
            'AM',
            'AO',
            'AR',
            'AT',
            'AU',
            'AZ',
            'BA',
            'BB',
            'BD',
            'BE',
            'BF',
            'BG',
            'BH',
            'BI',
            'BJ',
            'BN',
            'BO',
            'BR',
            'BS',
            'BT',
            'BW',
            'BY',
            'BZ',
            'CA',
            'CD',
            'CG',
            'CH',
            'CI',
            'CL',
            'CM',
            'CO',
            'CR',
            'CV',
            'CW',
            'CY',
            'CZ',
            'DE',
            'DJ',
            'DK',
            'DM',
            'DO',
            'DZ',
            'EC',
            'EE',
            'EG',
            'ES',
            'FI',
            'FJ',
            'FM',
            'FR',
            'GA',
            'GB',
            'GD',
            'GE',
            'GH',
            'GM',
            'GN',
            'GQ',
            'GR',
            'GT',
            'GW',
            'GY',
            'HK',
            'HN',
            'HR',
            'HT',
            'HU',
            'ID',
            'IE',
            'IL',
            'IN',
            'IQ',
            'IS',
            'IT',
            'JM',
            'JO',
            'JP',
            'KE',
            'KG',
            'KH',
            'KI',
            'KM',
            'KN',
            'KR',
            'KW',
            'KZ',
            'LA',
            'LB',
            'LC',
            'LI',
            'LK',
            'LR',
            'LS',
            'LT',
            'LU',
            'LV',
            'LY',
            'MA',
            'MC',
            'MD',
            'ME',
            'MG',
            'MH',
            'MK',
            'ML',
            'MN',
            'MO',
            'MR',
            'MT',
            'MU',
            'MV',
            'MW',
            'MX',
            'MY',
            'MZ',
            'NA',
            'NE',
            'NG',
            'NI',
            'NL',
            'NO',
            'NP',
            'NR',
            'NZ',
            'OM',
            'PA',
            'PE',
            'PG',
            'PH',
            'PK',
            'PL',
            'PS',
            'PT',
            'PW',
            'PY',
            'QA',
            'RO',
            'RS',
            'RW',
            'SA',
            'SB',
            'SC',
            'SE',
            'SG',
            'SI',
            'SK',
            'SL',
            'SM',
            'SN',
            'SR',
            'ST',
            'SV',
            'SZ',
            'TD',
            'TG',
            'TH',
            'TJ',
            'TL',
            'TN',
            'TO',
            'TR',
            'TT',
            'TV',
            'TW',
            'TZ',
            'UA',
            'UG',
            'US',
            'UY',
            'UZ',
            'VC',
            'VE',
            'VN',
            'VU',
            'WS',
            'XK',
            'ZA',
            'ZM',
            'ZW',
          ],
          external_urls: {
            spotify: 'https://open.spotify.com/album/4rdkuEThqNcw4ftMKf4McR',
          },
          href: 'https://api.spotify.com/v1/albums/4rdkuEThqNcw4ftMKf4McR',
          id: '4rdkuEThqNcw4ftMKf4McR',
          images: [
            {
              height: 640,
              url: 'https://i.scdn.co/image/ab67616d0000b273f73c9d1f767ae613e2bde3b4',
              width: 640,
            },
            {
              height: 300,
              url: 'https://i.scdn.co/image/ab67616d00001e02f73c9d1f767ae613e2bde3b4',
              width: 300,
            },
            {
              height: 64,
              url: 'https://i.scdn.co/image/ab67616d00004851f73c9d1f767ae613e2bde3b4',
              width: 64,
            },
          ],
          name: 'Dykhtau',
          release_date: '2021-12-17',
          release_date_precision: 'day',
          total_tracks: 1,
          type: 'album',
          uri: 'spotify:album:4rdkuEThqNcw4ftMKf4McR',
        },
        artists: [
          {
            external_urls: {
              spotify: 'https://open.spotify.com/artist/2HwBdENnqvDpXaeLBMBtqF',
            },
            href: 'https://api.spotify.com/v1/artists/2HwBdENnqvDpXaeLBMBtqF',
            id: '2HwBdENnqvDpXaeLBMBtqF',
            name: 'Sezja',
            type: 'artist',
            uri: 'spotify:artist:2HwBdENnqvDpXaeLBMBtqF',
          },
        ],
        available_markets: [
          'AD',
          'AE',
          'AG',
          'AL',
          'AM',
          'AO',
          'AR',
          'AT',
          'AU',
          'AZ',
          'BA',
          'BB',
          'BD',
          'BE',
          'BF',
          'BG',
          'BH',
          'BI',
          'BJ',
          'BN',
          'BO',
          'BR',
          'BS',
          'BT',
          'BW',
          'BY',
          'BZ',
          'CA',
          'CD',
          'CG',
          'CH',
          'CI',
          'CL',
          'CM',
          'CO',
          'CR',
          'CV',
          'CW',
          'CY',
          'CZ',
          'DE',
          'DJ',
          'DK',
          'DM',
          'DO',
          'DZ',
          'EC',
          'EE',
          'EG',
          'ES',
          'FI',
          'FJ',
          'FM',
          'FR',
          'GA',
          'GB',
          'GD',
          'GE',
          'GH',
          'GM',
          'GN',
          'GQ',
          'GR',
          'GT',
          'GW',
          'GY',
          'HK',
          'HN',
          'HR',
          'HT',
          'HU',
          'ID',
          'IE',
          'IL',
          'IN',
          'IQ',
          'IS',
          'IT',
          'JM',
          'JO',
          'JP',
          'KE',
          'KG',
          'KH',
          'KI',
          'KM',
          'KN',
          'KR',
          'KW',
          'KZ',
          'LA',
          'LB',
          'LC',
          'LI',
          'LK',
          'LR',
          'LS',
          'LT',
          'LU',
          'LV',
          'LY',
          'MA',
          'MC',
          'MD',
          'ME',
          'MG',
          'MH',
          'MK',
          'ML',
          'MN',
          'MO',
          'MR',
          'MT',
          'MU',
          'MV',
          'MW',
          'MX',
          'MY',
          'MZ',
          'NA',
          'NE',
          'NG',
          'NI',
          'NL',
          'NO',
          'NP',
          'NR',
          'NZ',
          'OM',
          'PA',
          'PE',
          'PG',
          'PH',
          'PK',
          'PL',
          'PS',
          'PT',
          'PW',
          'PY',
          'QA',
          'RO',
          'RS',
          'RW',
          'SA',
          'SB',
          'SC',
          'SE',
          'SG',
          'SI',
          'SK',
          'SL',
          'SM',
          'SN',
          'SR',
          'ST',
          'SV',
          'SZ',
          'TD',
          'TG',
          'TH',
          'TJ',
          'TL',
          'TN',
          'TO',
          'TR',
          'TT',
          'TV',
          'TW',
          'TZ',
          'UA',
          'UG',
          'US',
          'UY',
          'UZ',
          'VC',
          'VE',
          'VN',
          'VU',
          'WS',
          'XK',
          'ZA',
          'ZM',
          'ZW',
        ],
        disc_number: 1,
        duration_ms: 188500,
        episode: false,
        explicit: false,
        external_ids: {
          isrc: 'SE5W32104080',
        },
        external_urls: {
          spotify: 'https://open.spotify.com/track/6Dzybyg4sWgI3lDNsflTqn',
        },
        href: 'https://api.spotify.com/v1/tracks/6Dzybyg4sWgI3lDNsflTqn',
        id: '6Dzybyg4sWgI3lDNsflTqn',
        is_local: false,
        name: 'Dykhtau',
        popularity: 54,
        preview_url:
          'https://p.scdn.co/mp3-preview/707483a345170835393076b44b649e743b80a6fe?cid=774b29d4f13844c495f206cafdad9c86',
        track: true,
        track_number: 1,
        type: 'track',
        uri: 'spotify:track:6Dzybyg4sWgI3lDNsflTqn',
      },
      video_thumbnail: {
        url: null,
      },
    },
  ],
  limit: 1,
  next: 'https://api.spotify.com/v1/playlists/37i9dQZF1DXdVyc8LtLi96/tracks?offset=1&limit=1&locale=en-US,en;q=0.9,ko-KR;q=0.8,ko;q=0.7',
  offset: 0,
  previous: null,
  total: 298,
};
