#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

bun run lint:check || npm run lint:check
bun run build || npm run build
bun run test:run || npm run test:run
bun run size || npm run size
git add size.json
